import java.security.NoSuchAlgorithmException;

public class BlobTester {
    public static void main(String[] args) throws NoSuchAlgorithmException {
        System.out.println("HashCode Generated by SHA-1 for: ");

        String s1 = "GeeksForGeeks";
        System.out.println("\n" + s1 + " : " + Blob.doSha(s1));

        String s2 = "hello world";
        System.out.println("\n" + s2 + " : " + Blob.doSha(s2));
    }
}
