import java.io.IOException;
import java.security.NoSuchAlgorithmException;

public class BlobTester {
    public static void main(String[] args) throws NoSuchAlgorithmException, IOException {
        System.out.println("HashCode Generated by SHA-1 for: ");

        Blob testy = new Blob("test2.txt");
        testy.makeBlob();
    }
}
